# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build list.txt
      run: |
        rm -f list.txt
        touch list.txt
        for url in $(cat target.txt)
        do
          echo -e "duckduckgo.com##div:-abp-has(> div > h2 > a[href^=\"$url\"])\nwww.google.*##div:-abp-has(> div > div > a[href^=\"$url\"])\nwww.bing.com##li:-abp-has(> h2 > a[href^=\"$url\"])" >> list.txt
        done

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto build by gh-actions